### ISSUE TITLE
RepeatSensor interval not configurable

### ISSUE THREAD

**Issue by avanlievenoogen** [SignalK/SensESP#644]
Is there a way to make the interval configurable? Like for instance with the DigitalInputCounter read_delay?

**Comment by ba58smith** [comment]
It is already configurable, in that you set the delay in the constructor:
`RepeatSensor<T>(unsigned int repeat_interval_ms, std::function<T()> callback)`.
If you mean you'd like it to be configurable at run time, from the Config UI, I'm sure that would be possible, but not sure how high a priority it would be, since you can just change it in `main.cpp`.

**Comment by avanlievenoogen** [comment]
thanks for your response. I did mean configurable at run time and I agree, it is not really an issue. I just noticed it to be different than the other sensors and wanted to make sure I was not missing something.
